import { randomUUID } from "node:crypto";
import { constants } from "node:fs";
import { mkdir, open, unlink } from "node:fs/promises";
import type { FileHandle } from "node:fs/promises";
import { join } from "node:path";
import { Readable } from "node:stream";
import { pipeline } from "node:stream/promises";
import type { Config } from "../config.ts";
import type { MediaStorage } from "./storage.ts";

// Keys are generated by this adapter; never interpret a caller's key as a path.
const storageKeyPattern =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/;

function isFileExistsError(error: unknown): boolean {
  return error instanceof Error && "code" in error && error.code === "EEXIST";
}

function filePath(directory: string, key: string): string {
  if (!storageKeyPattern.test(key)) {
    throw new TypeError("Invalid media storage key.");
  }
  return join(directory, key);
}

async function createFile(
  directory: string,
): Promise<{ key: string; path: string; file: FileHandle }> {
  // Exclusive creation protects existing files even in the unlikely event of a UUID collision.
  for (let attempt = 0; attempt < 3; attempt++) {
    const key = randomUUID();
    const path = filePath(directory, key);
    try {
      const file = await open(
        path,
        constants.O_WRONLY |
          constants.O_CREAT |
          constants.O_EXCL |
          constants.O_NOFOLLOW,
        0o600,
      );
      return { key, path, file };
    } catch (error) {
      if (!isFileExistsError(error)) throw error;
    }
  }
  throw new Error("Unable to allocate media storage key.");
}

export function createLocalMediaStorage(
  config: Pick<Config, "MEDIA_STORAGE_DIRECTORY">,
): MediaStorage {
  const directory = config.MEDIA_STORAGE_DIRECTORY;
  return {
    async save(data): Promise<string> {
      await mkdir(directory, { recursive: true });
      const { key, path, file } = await createFile(directory);

      try {
        await pipeline(Readable.from(data), file.createWriteStream());
      } catch (error) {
        await file.close();
        await unlink(path);
        throw error;
      }
      return key;
    },
    async get(key): Promise<AsyncIterable<Uint8Array>> {
      const file = await open(
        filePath(directory, key),
        constants.O_RDONLY | constants.O_NOFOLLOW,
      );
      return file.createReadStream();
    },
    async delete(key): Promise<void> {
      await unlink(filePath(directory, key));
    },
  };
}
